# Generated by Django 4.2.6 on 2026-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
