# Generated by Django 6.0.2 on 2026-02-27 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cancel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
